import sqlite3
conn=sqlite3.connect('dbcollege26.db')
print('connected')
conn.execute('create table tblstud(rno int,name varchar2(10))')
print('table created')
conn.execute("insert into tblstud values(1,'fenil')")
conn.execute("insert into tblstud values(2,'jenil')")
conn.execute("insert into tblstud values(3,'mit')")
conn.execute('commit')
print('record inserted')